apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-ssm-keycloak
spec:
  provider:
    aws:
      service: ParameterStore
      region: PLACEHOLDER  # Will be replaced by Kustomize
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: keycloak
