apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Pin CloudNativePG to stable-v1
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-v1'
    target:
      kind: Subscription
      name: cloudnative-pg

  # Pin External Secrets to stable
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
    target:
      kind: Subscription
      name: external-secrets-operator
